--- #YAML:1.0
name:               mkthumbs
version:            1.03
abstract:           Makes thumbnails in .thumbnails dir. Suitable for gqview etc.
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Which:          0.05
    Getopt::Std::Strict:  1.01
    LEOCHARRE::Dir:       1.08
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
